/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/layouts/defaultLayout.vue')['default']
    Hello: typeof import('./src/views/Hello.vue')['default']
    OuterBox: typeof import('./src/components/OuterBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgGenerator: typeof import('./src/components/SvgGenerator.vue')['default']
    Tiny: typeof import('./src/components/Tiny.vue')['default']
  }
}
